name    'jaredhatfield-sendmailses'
version '0.0.3'
source 'https://github.com/JaredHatfield/puppet-sendmailses'
author 'jaredhatfield'
license 'Apache License, Version 2.0'
summary 'Configures sendmail to use SES on Amazon Linux'
description ''
project_page 'https://github.com/JaredHatfield/puppet-sendmailses'
